services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rag_api
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
    env_file:
      - .env  

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: rag_ui
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env  
